name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: regflotacombustible.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t regflotacombustible.azurecr.io/streamlit-app:latest .
        docker push regflotacombustible.azurecr.io/streamlit-app:latest

    - name: Update Azure Container Instance
      run: |
        az container update \
          --resource-group "prod-nuevo" \
          --name "contenedor-flota-v6" \
          --image regflotacombustible.azurecr.io/streamlit-app:latest \
          --set containers[0].environmentVariables=[{"name":"DB_USER_INDICADORES","secureValue":"srios"},{"name":"DB_PASS_INDICADORES","secureValue":"Sebastian2026"},{"name":"DB_USER_QAS","secureValue":"calidadsa"},{"name":"DB_PASS_QAS","secureValue":"Exalmar\$2026"}]